### ISSUE TITLE
Little CLI tool?

### ISSUE THREAD

**Issue by jmeas** [babel/babel-library-boilerplate#100]
So the technical benefits of moving to a system like Yeoman are clear, but I'm worried that it would turn off too many potential users. I want to have the discussion about what we would get from a dead-simple CLI tool. Just something to, say, update the license name and maybe a few commands to update the extra fields in package.json.

Cons:

- We write our own CLI tool
- Would it be global? Probably no, right? And if it's in the project...who wants to check that into git? Maybe it could add itself to `gitignore` so that you can keep it locally? Dunno.
- Not as powerful as Yeoman
- We write our own CLI tool

Pros:

- We could get a lot of the value of Yeoman w.o. using Yeoman

I personally have nothing against Yeoman...it's just that I don't think generators are very popular.

//cc @thejameskyle @paulfalgout

**Comment by thejameskyle** [comment]
Another benefit of a yeoman generator: know exactly how many people are using the project

**Comment by thejameskyle** [comment]
It also might make sense to put all the boilerplate files in it's own directory

```
boilerplate/
  src/
  test/
  .gitignore
  .jshintrc
  README.md
  LICENSE
  ...
README.md
LICENSE
...
```

**Comment by jmeas** [comment]
Closing in favor of yeoman. ref https://github.com/babel/babel-library-boilerplate/issues/58#issuecomment-85282361
