### ISSUE TITLE
Travis not failing on failed test

### ISSUE THREAD

**Issue by paulfalgout** [babel/babel-library-boilerplate#125]
If a failed test happens it keeps on trucking to a success state.  plumber maybe?

Pay little attention to the library.  WIP.  

https://travis-ci.org/RoundingWellOS/marionette.toolkit/builds/52438697

**Comment by jmeas** [comment]
oh, interesting. I'll look into this this weekend.

**Comment by nicksrandall** [comment]
I'm seeing the same issue. My gulp coverage task is throwing errors that I can't seem to track down. I'd love to help solve the problem if you could point me in the right direction.

https://travis-ci.org/nicksrandall/kotojs

**Comment by jmeas** [comment]
Resolved in master. For me, upgrading is usually as simple as copy+pasting the new Gulpfile.
