### ISSUE TITLE
Gulp coverage is throwing errors

### ISSUE THREAD

**Issue by nicksrandall** [babel/babel-library-boilerplate#127]
Related to #125 

The `gulp coverage` task is throwing an error in travis for every file it tries to run coverage on. This is probably a problem with one of the dependencies.

**Comment by jmeas** [comment]
> This is probably a problem with one of the dependencies.

This makes sense. In a webapp I have that has evolved side-by-side with this boilerplate, there are no errors. I'll compare the dependencies and see what I can come up with.

You can follow along over in #126

**Comment by nicksrandall** [comment]
It looks like the error is coming from isparta. I'm trying to get to the bottom of it.

**Comment by nicksrandall** [comment]
A pull request is in to fix the issue. As soon as isparta merges it in... this issue can be closed.
https://github.com/douglasduteil/isparta/pull/23

**Comment by jmeas** [comment]
@nicksrandall, thanks **a lot** for investigating!

**Comment by jmeas** [comment]
I'll get a release out today that fixes the problem.

**Comment by jmeas** [comment]
Resolved in master!
