### ISSUE TITLE
Best practice:  How to use multiple libraries together?

### ISSUE THREAD

**Issue by CollinEstes** [babel/babel-library-boilerplate#130]
Hey great boilerplate, so I was playing around with it last night and made a couple separate libraries with it.  I came to a point when I wanted to use one of the libraries I created within another.  (All in Node.js).  

What is the best practice for adding interdependences between libraries made with this boilerplate?

I tried just doing a local npm install:  
'npm install .../otherModule/' 

Which loaded it into my node_modules but when I went to use it like:
"import otherModule from 'otherModule' "
It would throw an error because it had no idea what otherModule was.

**Comment by jmeas** [comment]
This question is less about this boilerplate, and more about the general issue about how to use modules in node. A quick answer is that you probably want to register the packages on `npm` and load them from there, with the command `npm install name-of-my-package`. If you have other Q's related to working with node modules, I'd recommend asking them on StackOverflow. This issue tracker is for issues with this repo specifically.
