### ISSUE TITLE
Support cjs/amd export without global export

### ISSUE THREAD

**Issue by paulfalgout** [babel/babel-library-boilerplate#131]
For instance in `Backbone.Radio` "Radio" is not attached to root, but you can still:
`var Radio = require('backbone.radio')`

With this boilerplate if you export it is all or nothing.

Not sure if this is a limitation of esperanto or what, but it'd be a nice to have option.

**Comment by jmeas** [comment]
[?](https://github.com/babel/babel-library-boilerplate#i-dont-want-to-export-a-variable)

**Comment by paulfalgout** [comment]
If you were to convert backbone.radio to babel boilerplate,  and added it via a script tag it would be available via backbone.radio and window.radio.  The latter is not true with radio in its current state.

**Comment by jmeas** [comment]
You sure? I think I do what you're describing [here](https://github.com/jmeas/moment-business/blob/master/dist/moment-business.js#L2).

**Comment by paulfalgout** [comment]
So correct me if I'm wrong here, but with this, while its not available globally via a `<script>` tag and only attached to moment, this does not allow you to do:
```js
var something = require('moment-business');
```

With Radio you can both require it into a variable, and not expect it to be in the global namespace if added via script

**Comment by jmeas** [comment]
Oooh, it's finally coming together. I see what you mean. Good point.

> Not sure if this is a limitation of esperanto or what, but it'd be a nice to have option.

Would you care to look into whether Esperanto supports it or not?

**Comment by paulfalgout** [comment]
Turns out this is relatively easy and already supported.

https://github.com/esperantojs/esperanto/issues/126

For my use-case for instance this was simply:

```js
"babelBoilerplateOptions": {
    "entryFileName": "marionette.toolkit",
    "exportVarName": "Marionette.Toolkit",
...
```
