### ISSUE TITLE
Multiple named exports?

### ISSUE THREAD

**Issue by dstaley** [babel/babel-library-boilerplate#147]
So, from the readme I know that this is geared towards a single export. However, if I wanted to test multiple named exports, what changes would I need to make? I basically have a main module that I'd like to test, but then have three to five small helper functions I'd like to test separately as well.

Something like:
```js
export class Query {}
export function mean() {}
export function percentile() {}
export function time() {}
```

**Comment by jmeas** [comment]
Dunno — never done it. If you find out, you should write a wiki page about it!

**Comment by dstaley** [comment]
Okay so according to the [Esperanto docs](https://github.com/esperantojs/esperanto/wiki/Strict-mode), enabling multiple named exports is as easy as adding `strict: true` to the `bundle.toUmd` options in the gulp build step. After adding that I was able to export multiple functions from index.js and write unit tests for them as well. @jmeas would you still like to see a wiki page on this?

**Comment by jmeas** [comment]
*Shrug*. It could be useful for others, though they might also just find this issue. For now, I'm gonna close this.

**Comment by hliyan** [comment]
@dstaley , I was trying to do a `export a, b, c;` myself and ran into the same issue. I guess I'll be doing a single export then. Thanks for raising the question.

**Comment by jmeas** [comment]
fwiw Esperanto is deprecated, so I'm working on moving away from it to either just Babel, or Rollup, or ...somethin'
