### ISSUE TITLE
integrate phantomJS?

### ISSUE THREAD

**Issue by marcorra** [babel/babel-library-boilerplate#149]
@jmeas Can you integrate phantomjs with this boilerplate? Useless if you can't access document and window. 

Your whole setup do it very hard for other to integrate anything on this boilerplate.

This is my failure steps and 5 hour lost of time:

First of all tutorials and other expertise advices and stackoverflow fails.

Then... I have hard time doing a integration with your setup. I see there are no possibilities to merge this with your browserify, because that one is not used on tests. The tutorials you find with Google point you here.
Anyway. You need to open port 3000. For this I tried browser-sync, and linked it to  the tests/runner.html. A browsers pops up, but no phantomjs.

So next...
Then we have to look at that browserif you are not using in tests and your two test taks. This sens me to the test/setup/setup.js and node.js in same folder.  

I guess it's inside here somewhere you need to add in PhantomJS?

For if you look into the runner.html - a file that should have been launched with phantomjs, there is no way as I see it to launch phantomjs from here.

So I'm confused and therefor I ask you to implement this.

In the real world is just to open port 3000, install phantomjs and integrate it the normal way inside the gulp.js file.

Not possible here.

To simplify this. I just tried this once from scratch with a tutorial found on Google. Took me 2 minutes to set up and fully working. 5 hours tries with this boilerplate and no success

If it helps, this error message I get most of the time:

Error loading resource http://localhost:35729/livereload.js (1). Details: Connection refused
Failed to start mocha: Init timeout
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///E:/xampp12/htdocs/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee. Domains, protocols and ports must match.

And I also tried to change protocols and ports.

**Comment by jmeas** [comment]
@marcorra, not every project needs Phantom/JSDom, so I don't plan to add either of those to the boilerplate at the moment. Also, I personally prefer JSDom, as it's much faster and generally does everything I want. Sorry this has ended up being so difficult for you to set up!

If anyone else finds this issue who uses PhantomJS, maybe they can add a wiki / help you out. I just don't have the time right now, I'm afraid : [

**Comment by marcorra** [comment]
@jmeas I just moved on from this boilerplate. What else should I do? When no wiki or tutorials or Stackoverflow can help you / guide you to set up this things on your boilerplate. Then there are some errors a place.

And I printed out that error I got, and I also know why I got it. But again, that can't be done either as the tutorials told me.

So..

**Comment by marcorra** [comment]
@jmeas For other who read this, I can mention that this tutorial is the closest you can get help with phantomJS setup:  https://blog.gaya.ninja/articles/testing-javascript-browsersync-mocha-phantomjs/

Problems here are the things you need to setup in the .html file. That is done inside .js files with this boilerplate. AND if you follow this it will throw the errors shown earlier.

**Comment by marcorra** [comment]
@jmeas Last thing in this case. Some of the errors I got during my attempt is related to this: 

https://github.com/babel/babel-library-boilerplate/issues/141

You pointed out 25 days ago in your boilerplate and you haven't fixed it yet!!??

So there are obvious bugs in this crap, that prevent phantomjs integration

**Comment by Kflash** [comment]
@marcorra it's easier to setup your own solution. At least you need to open correct port. But as you pointed out pointed out there seem to be bugs. @jmeas haven't made it easy to integrate this. Not me either understand fully his thoughts. Maybe he should create a branch for it?

Anyway. Using 5 hours on something you call crap is for me amazing, and the way you write your issue tells me you are very agressive. A github issue shall be short and only about the problem you have.

I can't help you with this issue. I'm not inside @jmeas complex brain.

**Comment by paulfalgout** [comment]
@marcorra using the boilerplate it took about 15 mins to successfully setup jsdom for tests.

Here's the project utilizing it for reference.

https://github.com/RoundingWellOS/marionette.toolkit

**Comment by Kflash** [comment]
@paulfalgout How did you manage to install jsdom? I used v.12 and downgraded to v.10 because install of jsdom throws.

Still after downgrade to NodeJS v. 10 I get this errors:

 ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp E

**Comment by Kflash** [comment]
@paulfalgout I figure out that you was smart enough to use v. 2 of jsDOM and that solve the issues above. I got it installed. 

Personally I don't think that is the bullet proof solution for the future. Ofc. it depends on the use case, but even jquery uses 3.1.2 now, and ios 5.x

**Comment by Kflash** [comment]
@marcorra The best solution for you is to find another boilerplate. @jmeas solution gives even me trouble now. Anyway. He insisting on jsDOM, and that gives you problem. See post above.

A quick temporary solution if you need to use this boilerplate could be  to use https://www.npmjs.com/package/jsdom-no-contextify

Then you get no contextify issues - issues you find a lot of info about if you keep googling.

For PhantomJS. Don't event try it unless you know what you do, and the author would not implement this, so go for another solution.

**Comment by marcorra** [comment]
@paulfalgout I gave this one up now after what I see happend with @Kflash and what he wrote. To complicated for me this.

@jmeas I'm putting up a warning on my blog.

**Comment by jmeas** [comment]
@marcorra / @kflash, I understand that this stuff can be difficult to set up. It really sucks, but it's the nature of trying to make so many complex tools work together, I think. I'm afraid I don't have the time to make every possible configuration of additions to it, so there's not much else I can help with about trying to integrate Phantom.

One thing to note is that this library isn't solely meant to be a plug-and-play thing. If plugging and playing works out for you, then that's great! But it's also meant to act as inspiration / guidance for setting up similar, but different build systems. If Phantom is difficult to get set up with the repo as-is, then maybe make a new build system and pull in pieces from this as you need them.

> But ended up loosing all my data, re-formating my computer and a fresh windows install after fucking up nodejs and npm. Can you put up a warning sign on your repo?

Oh, dang! I'm sorry to hear that! I don't think this is specific to this boilerplate, though. It sounds like a problem with node and npm. It'd be silly if every bit of software built on top of node and npm had to include a warning, I think? Maybe you should contact the NodeJS maintainers to see if they can put a warning on the node site.

> @jmeas I'm putting up a warning on my blog.

Alright! I don't know exactly what you're warning against, but if you think that will help others, then by all means go for it.

**Comment by jmeas** [comment]
For now, I'm going to close this issue as wontfix. Feel free to continue the discussion about Phantom integration in here.

If anyone comes up with concrete changes I can make to ease Phantom integration (without directly adding Phantom), do let me know and I'll do what I can to help out :)

**Comment by Kflash** [comment]
@jmeas I lost my data because of NPM and node because I was experimenting with different nodeJS versions to avoid problems I got with integrating jsDOM. That is not your fault. And for me personally this boilerplate is not an option, I put together my own babel workflow long time ago with jasmin and phantomJS. Not mocha.

I tried to help @marcorra out on replying to his questions.

**Comment by ahumphreys87** [comment]
@marcorra have you tried using karma? It makes setting up your test process really simple and integrates with phantomjs. 

I think pushing people down a particular test framework would a tad too opinionated for a boilerplate that aims to give people a nice structure for babel

**Comment by marcorra** [comment]
@ahumphreys87 Didn't try because I wanted to use this boilerplate because of the ES6 options in the test cases. But ending up giving me too much trouble, and now I lost my work because 2 days over deadline because of this boilerplate.

So I gave up this case, and just found the gun and will pull the trigger in a few sec... bye!

**Comment by Kflash** [comment]
@jmeas what a nice sunday!! @marcorra SERIOUSLY!!! Find yourself a mental hospital NOW. Don't go around and kill yourself coz of a Babel ES6 boilerplate and PhantomJS

**Comment by justmeandtaken** [comment]
@marcorra  are you alive???????  Hello!!??

Who's responsible for @marcorra death? @jmeas because of phantomJS ??

**Comment by thejameskyle** [comment]
I'm leaving this note here for historical purposes.

The Babel project has an [official code of conduct](https://github.com/babel/babel/blob/master/CODE_OF_CONDUCT.md) and the behavior seen here was severely inappropriate. Contributors to these projects do so out of their own desire and without much reward.

In the future, if anyone feels attacked or witnesses someone breaking the code of conduct within the Babel community, please feel free to contact me personally (me@thejameskyle.com) or open an issue and it will be dealt with.

Also, suicide and self-harm is not a joke. If it was meant seriously then I encourage you to call the National Suicide Prevention Lifeline at 1 (800) 273-8255.
