### ISSUE TITLE
use rimraf

### ISSUE THREAD

**Issue by Kflash** [babel/babel-library-boilerplate#158]
Try to use **rimraf** instead of clear ( *deprecated*) and del as in your package.json. This too can cause problems with **nodejs@newest**. Depends on the use case of this boilerplate.

This is an easy switch as shown here: https://github.com/Kflash/ES2015/blob/master/gulpfile.js#L73-L76

**Comment by jmeas** [comment]
Thanks for the issue @kflash!

> clear ( deprecated)

What is clear?

> This too can cause problems with nodejs@newest.

Can you be more explicit here? What problems?

**Comment by Kflash** [comment]
@jmeas You are not using clear. Clearing the console. And also gulp-clean as serve the same purpose as del state very clear about rimraf: closehttps://www.npmjs.com/package/gulp-clean

For your other question. I'm not a living lexicon, Google will help. But there have been issues where the folder got locked by the fs so you can't touch it anymore. As one thing. There are others too

**Comment by jmeas** [comment]
@kflash, [Gulp's documentation](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md) uses del in their example...so I think it's probably fine. Also, `del` uses `rimraf` under the hood.

**Comment by Kflash** [comment]
@jmeas  As I wrote earlier. I'm out of this, and your repo.

As and end, I copy this console messages I get with your del and your setup:

**[02:30:39] Error: EBUSY, unlink ...
  at Error (native)**

This error I got with current **clean** task

**Comment by Kflash** [comment]
@jmeas but Ofc I can be wrong when it comes to your use case. But with my over 30 years experience in this game I'm used to see wider. What fit for one person don't need to fit for another one. Errors you experience  another one probably would not see or find. Depends on the use case. Bye!

**Comment by jmeas** [comment]
@fklash, it looks like you switched back to `del` in your own modification of this boilerplate, so I'm going to assume this issue was resolved on your end. Gonna close for now. If any other Windows folks have issues, just leave a comment here and we can revisit the problem!
