### ISSUE TITLE
esLint integration

### ISSUE THREAD

**Issue by Kflash** [babel/babel-library-boilerplate#159]
@jmeas  I integrated ESLint successfully on my test project. You can copy & paste. Just make sure you also copy the .eslint file in the root.

You find the code here: https://github.com/Kflash/ES2015/blob/master/gulpfile.js#L81-L98

esLint now works for source files and the test unit files.

There is a little issue. The jsNotify is not working out of the box with esLint it seems. I will investigate later. Other things to do now.

**NOTE!** You have to adjust and set your own rules, and remove the old lint files in your repo

**Comment by jmeas** [comment]
@kflash, there's already an issue regarding ESLint over at #144. Gonna close this as a duplicate. I'll reference this when I go about adding ESLint, though, so thanks!

**Comment by Kflash** [comment]
Sure. No problem. And I'm now out of your project. My time ended. I figure
waste of time to help out.
