### ISSUE TITLE
Add babelrc

### ISSUE THREAD

**Issue by jmeas** [babel/babel-library-boilerplate#163]
[docs](https://babeljs.io/docs/usage/babelrc/)

**Comment by jmeas** [comment]
@thejameskyle, I think I'm gonna close this as wontfix for now. I'm a fan of using the `babelrc` to configure stuff, but atm it would just be an empty file. I think most people won't need to configure babel, so it would just be a file they would delete.

**Comment by thejameskyle** [comment]
The file wouldn't actually be empty, it'd be:

```
{
  "blacklist": ["useStrict"]
}
```

There's also the problem that if someone wanted to configure babel at all they'd have to update it in four places:

- https://github.com/babel/babel-library-boilerplate/blob/master/gulpfile.js#L82
- https://github.com/babel/babel-library-boilerplate/blob/master/gulpfile.js#L101
- https://github.com/babel/babel-library-boilerplate/blob/master/gulpfile.js#L118
- https://github.com/babel/babel-library-boilerplate/blob/master/gulpfile.js#L136

**Comment by jmeas** [comment]
:+1: k – will add
