### ISSUE TITLE
IE & Safari build issues

### ISSUE THREAD

**Issue by glued** [babel/babel-library-boilerplate#168]
When I build using the boilerplate the resulting library works in Chrome & Firefox but in IE I get an error `Promise is undefined` and in Safari I get `Can't find variable: Symbol` Do I need to configure the gulpfile differently from the default to make it compatible? I assume I need to add the polyfill? or do I use the runtime ?

**Comment by jmeas** [comment]
> I assume I need to add the polyfill?

[Yah](https://babeljs.io/docs/usage/polyfill/).

**Comment by jmeas** [comment]
Did that work @glued? :stuck_out_tongue:

**Comment by glued** [comment]
yeah I included the JS file `browser-polyfill.min.js` like the tests  and it works.
How would I add it automatically to the build in the gulpfile?

**Comment by glued** [comment]
actually, still didn't work in IE but now safari does now it throws:
`Unhandled promise rejection TypeError: Object doesn't support this action`
