### ISSUE TITLE
ESLint/JSCS shouldn't fail until task is complete

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel-library-boilerplate#169]
Right now if you run `npm test` and jshint fails it will exit before running the tests. This is really annoying when trying to work on tests as stuff like `console.log` can make it fail before running tests.

The build should still fail just at the very end after running everything else.

**Comment by jmeas** [comment]
PR it, and it will come

**Comment by megawac** [comment]
@jmeas this should be closeable

**Comment by jmeas** [comment]
What's changed @megawac?

**Comment by megawac** [comment]
jshint -> eslint

**Comment by megawac** [comment]
Nevermind didn't read the issue
