### ISSUE TITLE
Remove JSCS?

### ISSUE THREAD

**Issue by jmeas** [babel/babel-library-boilerplate#172]
ESLint seems to do the job well enough.

**Comment by hzoo** [comment]
If you still want to use jscs (I'm adding some es6 rules) you can use https://github.com/hzoo/babel-jscs just like babel-eslint for eslint

**Comment by jmeas** [comment]
Oh, nice. I'll look into this, @hzoo!

**Comment by hzoo** [comment]
I'm going to move it to https://github.com/jscs-dev/babel-jscs soon (got a failing test at the moment). I don't know if I want to do the npm package yet since it will fail on the latest version of jscs (will work on master and the next future release)

**Comment by megawac** [comment]
@hzoo whats the advantage of using JSCS with eslint?

**Comment by hzoo** [comment]
Not too much if ESLint covers all the style rules that you need; I think JSCS has more style rules since it focus only on that.
However, both have a way of extending other people's configs, creating your own custom rules, etc. At the moment, JSCS has a autofix feature that can be useful as well (right now only for whitespace).

**Comment by thejameskyle** [comment]
@hzoo Want to make a PR for switching to babel-jscs?

**Comment by hzoo** [comment]
Ok sure

**Comment by jmeas** [comment]
Babel-JSCS is now the default of JSCS, so we've effectively switched to using babel-jscs. I still want to do some research to see if it makes sense to keep both linters.

I'd love for there to Just Be One©.

**Comment by jmeas** [comment]
I took a look through the rules of both, and I do want some of what each provide out of the box. Since they now both fully support Babel, and since it's super easy to remove any one of them, I think I'll keep both for now.
