### ISSUE TITLE
Arrow functions break scope context in mocha testing

### ISSUE THREAD

**Issue by michaelBenin** [babel/babel-library-boilerplate#176]
For example:

```
describe('my webdriverio tests', () =>  {
  this.timeout(99999999);
```

Breaks.

**Comment by sebmck** [comment]
Yep, arrow functions "inherit" the `this` and `arguments` of their containing function. This is [documented](http://babeljs.io/docs/learn-es2015/#arrows) on the Babel docs and even includes a mention in the [FAQ](http://babeljs.io/docs/faq/#why-are-this-and-arguments-being-remapped-in-arrow-functions-). Just use a normal function.
