### ISSUE TITLE
Simplify src map

### ISSUE THREAD

**Issue by jmeas** [babel/babel-library-boilerplate#180]
see https://github.com/google/incremental-dom/pull/79#discussion_r35830004

**Comment by megawac** [comment]
:-1: https://github.com/google/incremental-dom/pull/79#discussion_r35833616

**Comment by jmeas** [comment]
lol https://github.com/google/incremental-dom/pull/79#discussion_r35833743

**Comment by thejameskyle** [comment]
[google/incremental-dom#79 (comment)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by jmeas** [comment]
aaaaahahahahhaa

**Comment by jmeas** [comment]
@jridgewell, thanks for the ping! This is great!
