### ISSUE TITLE
Use 6to5ify

### ISSUE THREAD

**Issue by jmeas** [babel/babel-library-boilerplate#42]
Right now, building for the browser tests involves outputting a temp file. I know, I know, this is not very Gulp-like. There just might be a way to get around this by using 6to5ify, but there are problems with the dynamic input name being required in w. browserify.

**Comment by jmeas** [comment]
This would be awesome, but it will require doing fancy stuff with the filename. Browserify doesn't support dynamic names, so I would likely need to create a `tmp` browserify.js file that gets built with gulp.template, which is *then* used to by browserify.

**Comment by thejameskyle** [comment]
huh?

**Comment by jmeas** [comment]
The name of the entrypoint to the app can be customized [with the config file](https://github.com/jmeas/es6-library-boilerplate/blob/master/config/index.json#L4). Dynamic requires [like this](https://github.com/jmeas/es6-library-boilerplate/blob/master/test/setup/node.js#L4) aren't supported by browserify. So the current 6to5 transform outputs the file to [a predictable location](https://github.com/jmeas/es6-library-boilerplate/blob/master/gulpfile.js#L83) that browserify can safely [require in](https://github.com/jmeas/es6-library-boilerplate/blob/master/test/setup/browserify.js#L4).

By using 6to5ify, I can't think of a way to support that dynamic entrypoint.

I'm still new to Gulp, so it's entirely possible that I'm missing an obvious solution here :)

**Comment by thejameskyle** [comment]
@jmeas There's ways of dealing with all of that, but as I started to type it out I thought that it might just be better to make the entry file always `index.js` which is sort of a Node/npm convention.

**Comment by jmeas** [comment]
True. I just prefer the customizability, so I want to figure out how to do this

**Comment by thejameskyle** [comment]
I'll see if I have time to make a PR for you tomorrow, it'll be faster than trying to explain it in a comment.

**Comment by jmeas** [comment]
You are superheroic

**Comment by jmeas** [comment]
Any updatez @thejameskyle?

**Comment by thejameskyle** [comment]
oh yeaaaah

**Comment by jmeas** [comment]
:question:

**Comment by jmeas** [comment]
This is no longer an issue.
