### ISSUE TITLE
yeoman

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel-library-boilerplate#58]
do it

**Comment by jmeas** [comment]
Meh. I tried Yeoman awhile ago, and it wasn't enough to hook me. I also do not know any developer that uses Yeoman generators regularly. Do you?

I'm worried whatever gains Yeoman gives me may not make up for the large # of people will be turned off by it being yeoman generator. Maybe a separate project?

**Comment by jmeas** [comment]
Gonna close for now, but if there's ever demand from this from a user I'd prob. make a separate repo for a generator.

**Comment by thejameskyle** [comment]
It's kinda silly without this. As it is now people would just have to copy all the files manually.

**Comment by jmeas** [comment]
> It's kinda silly without this. As it is now people would just have to copy all the files manually.

Yup. I'm not saying Yeoman doesn't make it easier. It's just the fact that nobody I know wants to use Yeoman.

**Comment by thejameskyle** [comment]
If I wanted to use this project then I'd want to use it via Yeoman. If I didn't want to use Yeoman, then I wouldn't want to use this library.

**Comment by jmeas** [comment]
That's fine, but I think some of the most popular boilerplate projects aren't yeoman generators. Just going off of stars, Angular's yeoman generator is the most with 3156. Only 4 total have over 1000. HTML5Boilerplate has nearly 30k stars; Backbone boilerplate has 4450 stars, and so on. I think if people wanted to use Yeoman, it would be really good, but from what I can see they just aren't as interested when the alternative is not adding another build tool to their process.

**Comment by thejameskyle** [comment]
> _Throws book at @jmeas_

**Comment by jmeas** [comment]
rofl

**Comment by thejameskyle** [comment]
> _Makes generator-es6-library-boilerplate and promotes it via 6to5 channels._
> _Gets more stars than @jmeas_

**Comment by jmeas** [comment]
hahahahaha

**Comment by jmeas** [comment]
I'll make a separate project

geeeeeez louise

**Comment by thejameskyle** [comment]
> _Repeatedly hits refresh on on @jmeas' repositories page, waiting for the repo to be created._

**Comment by jmeas** [comment]
you may be doing that for a few dayz

**Comment by jmeas** [comment]
I guess making this a yeoman generator is prolly a good idea.

**Comment by arthurvr** [comment]
I can do that if you want.

**Comment by arthurvr** [comment]
I definitely think it's a good idea :+1:

**Comment by arthurvr** [comment]
> I'm worried whatever gains Yeoman gives me may not make up for the large # of people will be turned off by it being yeoman generator. Maybe a separate project?

I know quite a few generators that have their boilerplate in another repo as the generator itself, although that limits functionality.

**Comment by jmeas** [comment]
@arthurvr, it may be even easier than you think. @megawac / @thejameskyle have it already converted in a separate repo. It just needs to be copy + pasted. I don't have tha link tho'

**Comment by megawac** [comment]
- https://github.com/thejameskyle/generator-es6-library-boilerplate (port of https://github.com/babel/babel-library-boilerplate) for browserify/general usage

- https://github.com/megawac/generator-babel-node (port of https://github.com/jmeas/es6-node-boilerplate) for node/io.js usage specifically.

Both need to be updated (e.g. jshint->eslint) before they can be considered to be merged
