### ISSUE TITLE
Add release task

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel-library-boilerplate#81]
Something like this https://github.com/6to5/6to5/blob/master/Makefile#L72-L95

**Comment by jmeas** [comment]
I've never used a release task before, so I want to think about it more before committing to it. My primary concern is that there might be many different ways the individual may want to release the library. And if we, say, make an `npm` specific release system, then it might deter users who may want to use it for internal projects, or something. Shrug. We should chat about it more.

**Comment by thejameskyle** [comment]
Make is wonderful for this sort of thing, you can give people a sensible default and they can easily customize it.

**Comment by thejameskyle** [comment]
ping @jmeas we should chat about this.

**Comment by jmeas** [comment]
Still wanna chat @thejameskyle?

**Comment by thejameskyle** [comment]
Definitely

**Comment by jmeas** [comment]
Spoke w. @thejameskyle about this today. He suggested that the release task just do:

```sh
npm version $(type)
git push origin --tags
npm publish
```

which is a sensible default, I think. It also provides a place for folks to add additional hooks, as they see fit. I am :+1: to it!

**Comment by thejameskyle** [comment]
Thinking a little more it would be good to do:

```sh
npm run build
git commit -m 'Build lib'
npm version $(type)
git push origin --tags
npm publish
```

**Comment by jmeas** [comment]
:+1:

**Comment by jmeas** [comment]
Gonna close this in favor of #179
